extends: ["xo", "prettier"]
env: {
  jest: true,
  node: true
}
rules: {
  prettier/prettier: warn,
  camelcase: 0
}
plugins: ["prettier"]
ignorePatterns:
  - "coverage"
  - "generators/app/templates"